### ISSUE TITLE
Log aps that aren't imported

### ISSUE THREAD

**Issue by MrAnderson-a** [timjsmith24/XIQ_CSV_Onboard#1]
Occasionally will get this message: Serial_Onboard.Main - INFO - Counts for completed run: totalExisting= 0, totalOnboard = 5, totalFailed = 14
however the aps that failed aren't logged, and is hard to figure out which ones failed.  Would you setup logging for the failed aps too?

**Comment by timjsmith24** [comment]
Sure, let me take a look at this. I think it's supposed to be adding them to the log file and marking them as failed in the new csv file. But I will take a look soon. There is also a newer API to onboard that I may switch to. It give more information if there are issues.

**Comment by timjsmith24** [comment]
I have just updated the script using the new advanced-onboard API.
The CSV will now need to include a floor_id for the device.
I've also added the ability to add a network policy id to have that assigned to the devices. That is optional, though.

If you have any other issues feel free to email or create another issue.

**Comment by MrAnderson-a** [comment]
Floor ID? As in map location is now required?  If so, I don't think that
would be ideal.  I usually set up those options on the adoption part, so
when they come online they fall into the right location based on IP etc.
Usually won't ever know what AP goes where until that happens.

**Comment by timjsmith24** [comment]
Yes, the advanced-onboarding API call requires the floor id. It also validates the onboarding process and returns errors if there are failures. 
The old onboard API just attempts to onboard but gives no response on success/failure. The old script waited a bit and checked the status, but sometimes the device would still be show of checked too soon before the backend processes worked 
Could you do a staging location and then move them to the correct floor when you know? 
Otherwise the old version of the script would be best. You could change the sleep time to wait and check if the onboards APs still exist. Around line 193 is a time.sleep(10). You could change that from 10 seconds to 60 or something. And see if the errors show up then.

**Comment by MrAnderson-a** [comment]
Probably staging floor would work, then the adoption should move them to correct floor.

Will give it a try next deployment we have.
________________________________

**Comment by MrAnderson-a** [comment]
Ok, tried onboarding aps and got errors.  Initially tried onboarding
switches and that didn't work either.  Here is the error message I got when
onboarding APs:
[image: image.png]
attached is the csv file I used.

I ended up using the old script just to get the devices into the customer
account.

Thanks.

**Comment by timjsmith24** [comment]
can you send these to my email? - tismith@extremenetworks.com
I am not able to see the csv or the image.

Looking at the script it would only work for APs. I will need to add a csv column to EXOS or VOSS to be able to onboard switches as well.
